### ISSUE TITLE
Are you planning to support selenium 4?

### ISSUE THREAD

**Issue by petrem** [ggozad/behaving#119]
Hello,

Given selenium 3 is not going to be supported (see e.g. discussion on https://github.com/SeleniumHQ/selenium/issues/8762), could you please tell us if you are planning to support selenium 4 and if so, if you have a roadmap?

Many thanks!

**Comment by ggozad** [comment]
Hey Petre,
Selenium 4 support is definitely desirable. There is nothing very concrete yet, mostly because we need to evaluate whether we want to break away from splinter or wait for them to do the heavy work. Contributions to this end would be most welcome, I would be happy to help if you want to push to that direction.

**Comment by ggozad** [comment]
Selenium 4 is now supported and all tests pass.

**Comment by petrem** [comment]
Oh wow that was fast. Thank you for the update.

**Comment by psysoo** [comment]
Hi, @ggozad  Thanks for supporting selenium 4. I was waiting for this too. 
just let you know I got the below error from 'poetry update'

```
 Because behaving (3.0.5) depends on selenium (3.141.0)
   and no versions of behaving match >3.0.5,<4.0.0, behaving (>=3.0.5,<4.0.0) requires selenium (3.141.0).
  So, because bdd depends on both behaving (^3.0.5) and selenium (^4.4.3), version solving failed.
```

**Comment by ggozad** [comment]
I've been a bit fast to declare this done. There are indeed a few quirks mostly depending on splinter releasing. But it's definitely close, I will reopen this and work on it as soon as I get some time.

**Comment by ggozad** [comment]
behaving finally runs on selenium 4 🎉
