### ISSUE TITLE
Why does the persona name get reused as the browser name?

### ISSUE THREAD

**Issue by ThrawnCA** [ggozad/behaving#136]
Why does `given_a_persona` in `behaving/personas/steps.py` reuse the persona name as the name of the browser to load? It makes no sense to me.

**Comment by ggozad** [comment]
Hey,
Not sure I understand the question. Personas are essentially browser sessions with the ability to hold some values.  So switching personas back and forth will start or re-use a browser session.

**Comment by ThrawnCA** [comment]
Is that really the only way they're meant to be used? It's not our approach. 

We define a persona for each test user in the system, with their credentials, email, etc, and then each test uses "Given X as the persona" to have the login details ready. There's no inherent tie to the browser session, although in a lot of cases they'll be correlated.

**Comment by ggozad** [comment]
> Is that really the only way they're meant to be used? It's not our approach.
> 
> We define a persona for each test user in the system, with their credentials, email, etc, and then each test uses "Given X as the persona" to have the login details ready. There's no inherent tie to the browser session, although in a lot of cases they'll be correlated.

Well isn't that exactly the case behaving covers? In each test when you say "Given Foo as the persona" you will start a session for Foo. All cookies, session storage whatever will be tied to Foo. If you happen to start another session for "Bar" in the same test it will not carry the credentials of Foo.

**Comment by ThrawnCA** [comment]
Well, we do have tests that try logging out as one user and then logging in as another.

This has primarily been a nuisance when we've had to manually create a Browser instance due to version conflicts between Selenium vs Behaving vs Splinter vs Python, though, so maybe it won't really be an issue longer term.
