### ISSUE TITLE
'WebDriver' object has no attribute 'switch_to_window'

### ISSUE THREAD

**Issue by galuszkak** [ggozad/behaving#27]
With new splinter test are failing because there isn't now method: 'switch_to_window'. I will try to fix that.

**Comment by galuszkak** [comment]
@ggozad i fix that in my fork forget to PR... If this is still applicable I will submit PR.

https://github.com/galuszkak/behaving/tree/django_17

**Comment by ggozad** [comment]
It should be fixed already. Can you please check with your PR as well?

**Comment by galuszkak** [comment]
Yes It's fixed.

Thanks a lot @ggozad !
