### ISSUE TITLE
 How to escape the quotes needed to parse the variable

### ISSUE THREAD

**Issue by faneye** [ggozad/behaving#35]
Hi,
Any idea how to escape the quotes needed(?) to parse the variables? Tried \{}/:[] with no result. 

Example:
Step "#hello_$randomday_$randommonth_$randomyear" - the variables are not parsed
Step " #hello_"$randomday" _ "$randommonth" _ "$randomyear" " - the variables are parsed but I got something like this -  #hello_ "1" _ "July" _"2015"

Thank you for your help with this,
Bogdan

**Comment by demetris-manikas** [comment]
Hi,
Looks like the regular expression used matches words and the underscore is considered to be part of a word in python regex (Search for \w in  https://docs.python.org/2/library/re.html). This is why your first try fails (the var names searched are $randomday_, $randommonth_ ).
The behavior for your second try is expected.

You can use any other character outside [a-zA-Z0-9_\] to format your string.

A workaround if you must use the underscore is to set a var to "_" and use it.
e.g.
        When I set "under" to "_"
        And I set "day" to "01"
        And I set "month" to "Feb"

        And I set "date" to "$day$under$month"
        Then "date" is set to "01_Feb"

Hope this helped
