### ISSUE TITLE
'WebDriver' object has no attribute 'is_text_present'

### ISSUE THREAD

**Issue by pbergonza** [ggozad/behaving#52]
Dear,

I´m new with behaving. Congrats for the hard work

I´m using:

@step(u'I should see "{text}" within {timeout:d} seconds')

from:

https://github.com/ggozad/behaving/blob/master/src/behaving/web/steps/basic.py

I receive the error:

'WebDriver' object has no attribute 'is_text_present'

could you check it please?

**Comment by ggozad** [comment]
Hey, all tests pass fine here, something must be foo-bared with your setup. ``is_text_present`` is a definitely a function of WebDriver.
Hard to say what is wrong in your setup though.
