### ISSUE TITLE
deployment of behaving 1.5.0 on PyPi is not installable

### ISSUE THREAD

**Issue by MihaiBalint** [ggozad/behaving#54]
https://pypi.python.org/pypi/behaving/ lists behaving 1.5.0 as deployed and available, however a 

$ pip install behaving==1.5.0 

fails with a 404 not found, with the logs saying it looked for the download in https://pypi.python.org/simple/behaving/ which only lists downloads up to behaving 1.4.1

Additionally, https://pypi.python.org/pypi/behaving/1.4.1 has a green download button, whereas https://pypi.python.org/pypi/behaving/1.5.0 is missing the button.

**Comment by ggozad** [comment]
Ops, sorry about that, I hadn't noticed. Released 1.5.1 with some new steps.
