### ISSUE TITLE
Can not clear text in input box

### ISSUE THREAD

**Issue by guoqiao** [ggozad/behaving#56]
I am using behaving for auto-testing.  I need to clear the text in a input box so I can check the error message.  I did this:

    When I fill in "field-name" with ""

However I got this error:

You can implement step definitions for undefined steps with these snippets:

@when(u'I fill in "field-name" with ""')
def impl(context):
    assert False

Set input box to empty is useful, hope this can be allowed.

**Comment by ggozad** [comment]
Hey!
You are right, if there is nothing in the quotes the step will not be recognised.
It would make me so happy if you made a PR with a step, something on the lines of 

When I clear the text of field "{name}"

It should be very easy to do so, just copy paste an existing step, add a test and update the README.
Let me know if you need help!

**Comment by guoqiao** [comment]
Hi ggozad, just forked the repo and try to add the clear text step, and it turns out there is already one since 2014.  However, it's not in the step list of the README file.  Just updated the README and created a PR. Thanks.
