### ISSUE TITLE
phantomjs parameters?

### ISSUE THREAD

**Issue by guustflater** [ggozad/behaving#62]
Is there an option to pass parameters (--ignore-ssl-errors=true) to phantomjs ?

tried it with a script, but phantomjs will not shutdown after completing the steps.
# !/bin/bash

/opt/phantomjs/phantomjs $@ --ignore-ssl-errors=true

**Comment by ggozad** [comment]
You would have to make a custom driver as we do say for chrome, cordova, electron etc. At the moment it uses the default phantomjs webdriver.
I will happily accept a PR on this, please let me know if it also fixes #61

**Comment by realopenit** [comment]
i have got this working for a single browser: " Given I enable single browser mode"

in features/environment.py add:

    def before_step(context,step):
        if step.name =='a browser':
            if not hasattr(context,'browser_args'):
                context.browser_args = {}
            if not 'service_args' in context.browser_args:
                context.browser_args['service_args'] = ['--ignore-ssl-errors=true']
            else:
                context.browser_args['service_args'].append('--ignore-ssl-errors=true')

**Comment by ggozad** [comment]
@realopenit but this fixes it only for that particular case. It should be merely a copy paste to add the flag in the driver. It's for flags like that that we introduced custom drivers for chrome cordova etc.
