### ISSUE TITLE
Scenario Outline and Example Tables

### ISSUE THREAD

**Issue by j7an** [ggozad/behaving#71]
How do I use 'behaving' with behave's scenario outline and example tables? Right now any Given, When, Then statements with '<>' are skipped and not processed by 'behaving'. I get an error steps are not implemented.

```
Given I should see <heading_on_page>
When I search for <query_in_search_field>
And I should see <text_in_search_result> within 15 seconds
And I click the link with text that contains <title>
Then I should see <text_in_document> within 10 seconds
```

If I copy the relevant steps from behaving into my own step file and remove the double quotes around the variable in the decoration, my outline passes.

```
@given(u'I should see {text}')
# @step(u'I should see "{text}"')
# @persona_vars
def should_see(context, text):
    assert context.browser.is_text_present(text), u'Text not found'
```

**Comment by j7an** [comment]
Adding double quotes around the brackets solved the problem. Weird the Behave documentation only has example without quotes around brackets.

```
    Given I should see "<heading_on_page>"
    When I search for "<query_in_search_field>"
    And I should see "<text_in_search_result>" within 15 seconds
    And I click the link with text that contains "<title>"
    Then I should see "<text_in_document>" within 10 seconds
```

Please update documentation for 'behaving' including outline examples as seen above.

**Comment by ggozad** [comment]
Could you please make a pr with this doc additions?
