### ISSUE TITLE
Provide a mechanism to override predefined steps

### ISSUE THREAD

**Issue by jagguli** [ggozad/behaving#73]
I am using steps from a 3rd party library  (behave_http)

Now I need to modify the behaviour of these steps specifically for my project

So in my steps I need a way to override the steps defined in the library.

Currently it errors out with an exception about duplicate step definition

**Comment by ggozad** [comment]
Can't you just selectively import the steps you need, i.e. not import behaving.web?

**Comment by jagguli** [comment]
I use other steps from behaving.web, and loading the module would register the steps because of decorator ?
