### ISSUE TITLE
mailmock not compatible with python 3.6

### ISSUE THREAD

**Issue by kgrecki** [ggozad/behaving#80]
error: uncaptured python exception, closing channel <smtpd.SMTPChannel connected 127.0.0.1:59782 at 0x7f0c411f0898> (<class 'TypeError'>:process_message() got an unexpected keyword argument 'mail_options' 

method signature needs two additional parameters mail_options and rcpt_options
possibly other changes as well

**Comment by ggozad** [comment]
Hey Karol,
Could you please make a PR? Please keep compatibility with 2.7.

**Comment by kgrecki** [comment]
I don't have a working fix for it at the moment. I'll get back to it when I can.
