### ISSUE TITLE
How to use Headless Browsers?

### ISSUE THREAD

**Issue by zmr01** [ggozad/behaving#88]
I want to use headless browser（firefox/chrome），how do i configure it？

eg:
Given a headless  browser

**Comment by ggozad** [comment]
Hey there, I think Chrome can run headless these days. You would need to add a driver (See chrome.py) for example and add whatever flags make it work.
Please submit a PR if you do so.

**Comment by ggozad** [comment]
On second thought, I think I might just implement that.
